#!/bin/bash

cd "${0%/*}"

MACOS=`dirname $0`
CONTENTS=`dirname $MACOS`
BIN=$CONTENTS/bin

PYTHONPATH=$CONTENTS/lib/python2.6
PYTHONPATH=$PYTHONPATH:$PYTHONPATH/site-packages
GDK_PIXBUF_MODULE_FILE=$CONTENTS/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
PANGO_RC_FILE=$CONTENTS/etc/pango/pango.modules
GTK_IM_MODULE_FILE=$CONTENTS/etc/gtk-2.0/gtk.immodules

export PYTHONPATH GDK_PIXBUF_MODULE_FILE PANGO_RC_FILE GTK_IM_MODULE_FILE

echo PATH: $PATH
echo ARGS: $*
echo -n env:
env

$BIN/python $BIN/gaphor
