#!/bin/bash

cd "${0%/*}"

MACOS=`dirname $0`
CONTENTS=`dirname $MACOS`
BIN=$CONTENTS/bin

PYTHONPATH=$CONTENTS/lib/python2.6
PYTHONPATH=$PYTHONPATH:$PYTHONPATH/site-packages

export PYTHONPATH

echo PATH: $PATH
echo ARGS: $*
echo -n env:
env

$BIN/python $BIN/gaphor
